import sys
import json
import shutil
import subprocess
from pathlib import Path

def run(cmd):
    print(f"CMD: {cmd}")
    subprocess.check_call(cmd, shell=True)

print("--- STARTING AUDIT P1-P4 ---")

# Setup paths
PYTHON = ".venv/bin/python"
XML_IN = "audit_sample.xml"
MIDI_IN = "samples/sample.mid"
DIFF_1 = "diff_1.json"
PATCH_1 = "patchplan.json"
XML_OUT_1 = "repaired_1.xml"
XML_OUT_2 = "repaired_2.xml"
DIFF_2 = "diff_2.json"

# Clean up previous artifacts
for f in [PATCH_1, XML_OUT_1, XML_OUT_2, DIFF_2]:
    if Path(f).exists():
        Path(f).unlink()

print("\n--- P1: Schema Validation ---")
# Generate Diff 1 (Fresh start)
run(f"{PYTHON} -m musicdiff --xml {XML_IN} --midi {MIDI_IN} --out {DIFF_1}")

# Generate Plan (Dry run)
run(f"{PYTHON} -m musicdiff.repair --diff {DIFF_1} --xml {XML_IN} --out {PATCH_1} --dry-run")

# Validate Schema
with open('contracts/patchplan.schema.json') as f:
    schema = json.load(f)
with open(PATCH_1) as f:
    plan = json.load(f)

# Use musicdiff internal validation or jsonschema if available
try:
    import jsonschema
    jsonschema.validate(instance=plan, schema=schema)
    print("✅ P1 PASS: Schema Valid")
except ImportError:
    print("⚠️ P1 SKIP: jsonschema not installed, assuming valid if generated by tool")

print(f"Plan contains {len(plan['operations'])} operations.")

print("\n--- P2: Idempotency ---")
# Apply 1: XML_IN + PATCH_1 -> XML_OUT_1
run(f"{PYTHON} -m musicdiff.repair --diff {DIFF_1} --xml {XML_IN} --out {PATCH_1} --apply --patched-out {XML_OUT_1}")

# Apply 2: XML_OUT_1 + PATCH_1 -> XML_OUT_2
# Use python script to call apply_patch_plan directly to bypass CLI requirement for --diff
apply_script = """
from musicdiff.repair.applier import apply_patch_plan
apply_patch_plan('repaired_1.xml', 'patchplan.json', 'repaired_2.xml')
print('Applied plan to repaired file.')
"""
run(f"{PYTHON} -c \"{apply_script}\"")

# Compare files
with open(XML_OUT_1, 'rb') as f1, open(XML_OUT_2, 'rb') as f2:
    content1 = f1.read()
    content2 = f2.read()

if content1 == content2:
    print("✅ P2 PASS: Idempotency verified (File 1 == File 2)")
else:
    print("❌ P2 FAIL: Files differ after second application")
    # For debugging, maybe print size diff
    print(f"Size 1: {len(content1)}, Size 2: {len(content2)}")


print("\n--- P3: Parse Check ---")
try:
    # We use a subprocess to run a python script that imports music21
    # This ensures we use the venv's music21
    parse_script = """
from music21 import converter
try:
    s = converter.parse('repaired_1.xml')
    print('P3_PASS: music21 parsed repaired file successfully')
    print(f'Note count: {len(s.recurse().notes)}')
except Exception as e:
    print(f'P3_FAIL: {e}')
    exit(1)
"""
    run(f"{PYTHON} -c \"{parse_script}\"")
except subprocess.CalledProcessError:
    print("❌ P3 FAIL: Parsing crashed")

# Debug P2 failure
if content1 != content2:
    debug_script = """
from music21 import converter
s1 = converter.parse('repaired_1.xml')
s2 = converter.parse('repaired_2.xml')
n1 = len(s1.recurse().notes)
n2 = len(s2.recurse().notes)
print(f'Repaired 1 Notes: {n1}')
print(f'Repaired 2 Notes: {n2}')
if n1 != n2:
    print('❌ P2 FAIL: Note count changed (Idempotency broken)')
else:
    print('⚠️ P2 WARN: Files differ but note count identical (likely formatting)')
"""
    run(f"{PYTHON} -c \"{debug_script}\"")


print("\n--- P4: Diff Reduction ---")
# Generate Diff 2 (Repaired vs MIDI)
run(f"{PYTHON} -m musicdiff --xml {XML_OUT_1} --midi {MIDI_IN} --out {DIFF_2}")

with open(DIFF_1) as f1, open(DIFF_2) as f2:
    d1 = json.load(f1)
    d2 = json.load(f2)

errors1 = len([d for d in d1['diffs'] if d['severity'] == 'error'])
errors2 = len([d for d in d2['diffs'] if d['severity'] == 'error'])

print(f"Initial Errors: {errors1}")
print(f"Final Errors:   {errors2}")

if errors2 < errors1:
    print("✅ P4 PASS: Error count reduced")
else:
    print("❌ P4 FAIL: Error count not reduced")

print("\n--- AUDIT COMPLETE ---")
